# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'base.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 600)
        MainWindow.setStyleSheet("background-color:rgb(230,230,230);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(-10, 0, 1051, 91))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(38)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("background-color:rgb(30,30,30);\n"
"color:white")
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 90, 1021, 371))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.frame_6 = QtWidgets.QFrame(self.page)
        self.frame_6.setGeometry(QtCore.QRect(345, 10, 331, 211))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 315, 41))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:white;\n"
"background-color:rgb(1, 255, 9);\n"
"border-top-left-radius:5px;\n"
"border-top-right-radius:5px;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setGeometry(QtCore.QRect(10, 30, 315, 171))
        self.frame_7.setStyleSheet("background-color:white;\n"
"border-radius:5px")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.cur_humid_1 = QtWidgets.QLabel(self.frame_7)
        self.cur_humid_1.setGeometry(QtCore.QRect(60, 40, 181, 71))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.cur_humid_1.setFont(font)
        self.cur_humid_1.setStyleSheet("background:transparent;\n"
"color:rgb(10,10,10);")
        self.cur_humid_1.setAlignment(QtCore.Qt.AlignCenter)
        self.cur_humid_1.setObjectName("cur_humid_1")
        self.line_2 = QtWidgets.QFrame(self.frame_7)
        self.line_2.setGeometry(QtCore.QRect(15, 130, 285, 1))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.line_2.setPalette(palette)
        self.line_2.setStyleSheet("background-color:rgb(220,220,220);\n"
"border:transparent")
        self.line_2.setLineWidth(0)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_9 = QtWidgets.QLabel(self.frame_7)
        self.label_9.setGeometry(QtCore.QRect(110, 140, 71, 21))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(13)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background:transparent;\n"
"color:rgb(10,10,10);")
        self.label_9.setObjectName("label_9")
        self.settings_humid = QtWidgets.QLabel(self.frame_7)
        self.settings_humid.setGeometry(QtCore.QRect(160, 140, 61, 21))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        self.settings_humid.setFont(font)
        self.settings_humid.setStyleSheet("background:transparent;\n"
"color:rgb(10,10,10);")
        self.settings_humid.setAlignment(QtCore.Qt.AlignCenter)
        self.settings_humid.setObjectName("settings_humid")
        self.label_16 = QtWidgets.QLabel(self.frame_7)
        self.label_16.setGeometry(QtCore.QRect(210, 140, 31, 21))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(13)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("background:transparent;\n"
"color:rgb(10,10,10);")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_19 = QtWidgets.QLabel(self.frame_7)
        self.label_19.setGeometry(QtCore.QRect(200, 60, 41, 41))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("background:transparent;\n"
"color:rgb(10,10,10);")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.frame_7.raise_()
        self.label_7.raise_()
        self.frame_8 = QtWidgets.QFrame(self.page)
        self.frame_8.setGeometry(QtCore.QRect(680, 10, 331, 211))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_11 = QtWidgets.QLabel(self.frame_8)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 315, 41))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color:white;\n"
"background-color:rgb(1, 255, 9);\n"
"border-top-left-radius:5px;\n"
"border-top-right-radius:5px;")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setGeometry(QtCore.QRect(10, 30, 315, 171))
        self.frame_9.setStyleSheet("background-color:white;\n"
"border-radius:5px")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.cur_co2_1 = QtWidgets.QLabel(self.frame_9)
        self.cur_co2_1.setGeometry(QtCore.QRect(60, 40, 181, 71))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.cur_co2_1.setFont(font)
        self.cur_co2_1.setStyleSheet("background:transparent;\n"
"color:rgb(10,10,10);")
        self.cur_co2_1.setAlignment(QtCore.Qt.AlignCenter)
        self.cur_co2_1.setObjectName("cur_co2_1")
        self.line_3 = QtWidgets.QFrame(self.frame_9)
        self.line_3.setGeometry(QtCore.QRect(10, 130, 281, 1))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.line_3.setPalette(palette)
        self.line_3.setStyleSheet("background-color:rgb(220,220,220);\n"
"border:transparent")
        self.line_3.setLineWidth(0)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_13 = QtWidgets.QLabel(self.frame_9)
        self.label_13.setGeometry(QtCore.QRect(110, 140, 71, 21))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(13)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background:transparent;\n"
"color:rgb(10,10,10);")
        self.label_13.setObjectName("label_13")
        self.settings_co2 = QtWidgets.QLabel(self.frame_9)
        self.settings_co2.setGeometry(QtCore.QRect(160, 140, 61, 21))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        self.settings_co2.setFont(font)
        self.settings_co2.setStyleSheet("background:transparent;\n"
"color:rgb(10,10,10);")
        self.settings_co2.setAlignment(QtCore.Qt.AlignCenter)
        self.settings_co2.setObjectName("settings_co2")
        self.label_17 = QtWidgets.QLabel(self.frame_9)
        self.label_17.setGeometry(QtCore.QRect(210, 140, 61, 21))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(13)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("background:transparent;\n"
"color:rgb(10,10,10);")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.frame_9)
        self.label_18.setGeometry(QtCore.QRect(210, 70, 71, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("background:transparent;\n"
"color:rgb(10,10,10);")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.frame_9.raise_()
        self.label_11.raise_()
        self.frame_13 = QtWidgets.QFrame(self.page)
        self.frame_13.setGeometry(QtCore.QRect(680, 220, 331, 151))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_30 = QtWidgets.QLabel(self.frame_13)
        self.label_30.setGeometry(QtCore.QRect(10, 10, 315, 41))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color:white;\n"
"background-color:rgb(1, 255, 9);\n"
"border-top-left-radius:5px;\n"
"border-top-right-radius:5px;")
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.frame_14 = QtWidgets.QFrame(self.frame_13)
        self.frame_14.setGeometry(QtCore.QRect(10, 30, 315, 111))
        self.frame_14.setStyleSheet("background-color:white;\n"
"border-radius:5px")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.sens_time = QtWidgets.QLabel(self.frame_14)
        self.sens_time.setGeometry(QtCore.QRect(50, 30, 211, 71))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.sens_time.setFont(font)
        self.sens_time.setStyleSheet("background:transparent;\n"
"color:rgb(10,10,10);")
        self.sens_time.setAlignment(QtCore.Qt.AlignCenter)
        self.sens_time.setObjectName("sens_time")
        self.frame_14.raise_()
        self.label_30.raise_()
        self.frame_3 = QtWidgets.QFrame(self.page)
        self.frame_3.setGeometry(QtCore.QRect(10, 220, 331, 151))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_26 = QtWidgets.QLabel(self.frame_3)
        self.label_26.setGeometry(QtCore.QRect(10, 10, 315, 41))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color:white;\n"
"background-color:rgb(1, 255, 9);\n"
"border-top-left-radius:5px;\n"
"border-top-right-radius:5px;")
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.frame_10 = QtWidgets.QFrame(self.frame_3)
        self.frame_10.setGeometry(QtCore.QRect(10, 30, 315, 111))
        self.frame_10.setStyleSheet("background-color:white;\n"
"border-radius:5px")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.progress = QtWidgets.QLabel(self.frame_10)
        self.progress.setGeometry(QtCore.QRect(60, 30, 181, 71))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.progress.setFont(font)
        self.progress.setStyleSheet("background:transparent;\n"
"color:rgb(10,10,10);")
        self.progress.setAlignment(QtCore.Qt.AlignCenter)
        self.progress.setObjectName("progress")
        self.label_31 = QtWidgets.QLabel(self.frame_10)
        self.label_31.setGeometry(QtCore.QRect(200, 50, 41, 41))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("background:transparent;\n"
"color:rgb(10,10,10);")
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.frame_10.raise_()
        self.label_26.raise_()
        self.frame_11 = QtWidgets.QFrame(self.page)
        self.frame_11.setGeometry(QtCore.QRect(345, 220, 331, 151))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_28 = QtWidgets.QLabel(self.frame_11)
        self.label_28.setGeometry(QtCore.QRect(10, 10, 315, 41))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color:white;\n"
"background-color:rgb(1, 255, 9);\n"
"border-top-left-radius:5px;\n"
"border-top-right-radius:5px;")
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.frame_12 = QtWidgets.QFrame(self.frame_11)
        self.frame_12.setGeometry(QtCore.QRect(10, 30, 315, 111))
        self.frame_12.setStyleSheet("background-color:white;\n"
"border-radius:5px")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.cur_time = QtWidgets.QLabel(self.frame_12)
        self.cur_time.setGeometry(QtCore.QRect(50, 30, 221, 71))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.cur_time.setFont(font)
        self.cur_time.setStyleSheet("background:transparent;\n"
"color:rgb(10,10,10);")
        self.cur_time.setAlignment(QtCore.Qt.AlignCenter)
        self.cur_time.setObjectName("cur_time")
        self.frame_12.raise_()
        self.label_28.raise_()
        self.frame = QtWidgets.QFrame(self.page)
        self.frame.setGeometry(QtCore.QRect(10, 10, 331, 211))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 315, 41))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;\n"
"background-color:rgb(1, 255, 9);\n"
"border-top-left-radius:5px;\n"
"border-top-right-radius:5px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(10, 30, 315, 171))
        self.frame_2.setStyleSheet("background-color:white;\n"
"border-radius:5px")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.cur_temp_1 = QtWidgets.QLabel(self.frame_2)
        self.cur_temp_1.setGeometry(QtCore.QRect(60, 40, 181, 71))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.cur_temp_1.setFont(font)
        self.cur_temp_1.setStyleSheet("background:transparent;\n"
"color:rgb(10,10,10);")
        self.cur_temp_1.setAlignment(QtCore.Qt.AlignCenter)
        self.cur_temp_1.setObjectName("cur_temp_1")
        self.line = QtWidgets.QFrame(self.frame_2)
        self.line.setGeometry(QtCore.QRect(15, 130, 285, 1))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.line.setPalette(palette)
        self.line.setStyleSheet("background-color:rgb(220,220,220);\n"
"border:transparent")
        self.line.setLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(110, 140, 71, 21))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background:transparent;\n"
"color:rgb(10,10,10);")
        self.label_5.setObjectName("label_5")
        self.settings_temp = QtWidgets.QLabel(self.frame_2)
        self.settings_temp.setGeometry(QtCore.QRect(160, 140, 61, 21))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(13)
        self.settings_temp.setFont(font)
        self.settings_temp.setStyleSheet("background:transparent;\n"
"color:rgb(10,10,10);")
        self.settings_temp.setAlignment(QtCore.Qt.AlignCenter)
        self.settings_temp.setObjectName("settings_temp")
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setGeometry(QtCore.QRect(210, 140, 31, 21))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(13)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("background:transparent;\n"
"color:rgb(10,10,10);")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_20 = QtWidgets.QLabel(self.frame_2)
        self.label_20.setGeometry(QtCore.QRect(200, 60, 41, 41))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("background:transparent;\n"
"color:rgb(10,10,10);")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.frame_2.raise_()
        self.label.raise_()
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.unfix_check = QtWidgets.QRadioButton(self.page_2)
        self.unfix_check.setGeometry(QtCore.QRect(940, 20, 61, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(12)
        self.unfix_check.setFont(font)
        self.unfix_check.setStyleSheet("background-color:transparent")
        self.unfix_check.setObjectName("unfix_check")
        self.fix_check = QtWidgets.QRadioButton(self.page_2)
        self.fix_check.setGeometry(QtCore.QRect(880, 20, 61, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(12)
        self.fix_check.setFont(font)
        self.fix_check.setStyleSheet("background-color:transparent")
        self.fix_check.setChecked(True)
        self.fix_check.setObjectName("fix_check")
        self.temp_check = QtWidgets.QCheckBox(self.page_2)
        self.temp_check.setGeometry(QtCore.QRect(230, 20, 81, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(12)
        self.temp_check.setFont(font)
        self.temp_check.setStyleSheet("background-color:transparent")
        self.temp_check.setChecked(True)
        self.temp_check.setObjectName("temp_check")
        self.humid_check = QtWidgets.QCheckBox(self.page_2)
        self.humid_check.setGeometry(QtCore.QRect(290, 20, 81, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(12)
        self.humid_check.setFont(font)
        self.humid_check.setStyleSheet("background-color:transparent")
        self.humid_check.setChecked(True)
        self.humid_check.setObjectName("humid_check")
        self.co2_check = QtWidgets.QCheckBox(self.page_2)
        self.co2_check.setGeometry(QtCore.QRect(350, 20, 81, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(12)
        self.co2_check.setFont(font)
        self.co2_check.setStyleSheet("background-color:transparent")
        self.co2_check.setChecked(True)
        self.co2_check.setObjectName("co2_check")
        self.frame_17 = QtWidgets.QFrame(self.page_2)
        self.frame_17.setGeometry(QtCore.QRect(20, 20, 181, 101))
        self.frame_17.setStyleSheet("background-color:red;\n"
"border-radius:5px")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.cur_temp_2 = QtWidgets.QLabel(self.frame_17)
        self.cur_temp_2.setGeometry(QtCore.QRect(30, 40, 101, 61))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.cur_temp_2.setFont(font)
        self.cur_temp_2.setStyleSheet("background:transparent;\n"
"color:white;")
        self.cur_temp_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cur_temp_2.setObjectName("cur_temp_2")
        self.line_6 = QtWidgets.QFrame(self.frame_17)
        self.line_6.setGeometry(QtCore.QRect(15, 40, 153, 1))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.line_6.setPalette(palette)
        self.line_6.setStyleSheet("background-color:rgb(220,220,220);\n"
"border:transparent")
        self.line_6.setLineWidth(0)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_38 = QtWidgets.QLabel(self.frame_17)
        self.label_38.setGeometry(QtCore.QRect(70, 10, 71, 21))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("background:transparent;\n"
"color:white;")
        self.label_38.setObjectName("label_38")
        self.label_40 = QtWidgets.QLabel(self.frame_17)
        self.label_40.setGeometry(QtCore.QRect(110, 50, 41, 51))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("background:transparent;\n"
"color:white;")
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.frame_18 = QtWidgets.QFrame(self.page_2)
        self.frame_18.setGeometry(QtCore.QRect(20, 140, 181, 101))
        self.frame_18.setStyleSheet("background-color:blue;\n"
"border-radius:5px")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.line_8 = QtWidgets.QFrame(self.frame_18)
        self.line_8.setGeometry(QtCore.QRect(15, 40, 153, 1))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.line_8.setPalette(palette)
        self.line_8.setStyleSheet("background-color:rgb(220,220,220);\n"
"border:transparent")
        self.line_8.setLineWidth(0)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.label_44 = QtWidgets.QLabel(self.frame_18)
        self.label_44.setGeometry(QtCore.QRect(70, 10, 71, 21))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("color:white\n"
"")
        self.label_44.setObjectName("label_44")
        self.label_41 = QtWidgets.QLabel(self.frame_18)
        self.label_41.setGeometry(QtCore.QRect(110, 50, 41, 51))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("background:transparent;\n"
"color:white;")
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.cur_humid_2 = QtWidgets.QLabel(self.frame_18)
        self.cur_humid_2.setGeometry(QtCore.QRect(30, 40, 101, 61))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.cur_humid_2.setFont(font)
        self.cur_humid_2.setStyleSheet("background:transparent;\n"
"color:white;")
        self.cur_humid_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cur_humid_2.setObjectName("cur_humid_2")
        self.frame_19 = QtWidgets.QFrame(self.page_2)
        self.frame_19.setGeometry(QtCore.QRect(20, 260, 181, 101))
        self.frame_19.setStyleSheet("background-color:grey;\n"
"border-radius:5px")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.line_9 = QtWidgets.QFrame(self.frame_19)
        self.line_9.setGeometry(QtCore.QRect(15, 40, 153, 1))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.line_9.setPalette(palette)
        self.line_9.setStyleSheet("background-color:rgb(220,220,220);\n"
"border:transparent")
        self.line_9.setLineWidth(0)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.label_47 = QtWidgets.QLabel(self.frame_19)
        self.label_47.setGeometry(QtCore.QRect(70, 10, 71, 21))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setStyleSheet("color:white")
        self.label_47.setObjectName("label_47")
        self.label_42 = QtWidgets.QLabel(self.frame_19)
        self.label_42.setGeometry(QtCore.QRect(100, 50, 81, 51))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("background:transparent;\n"
"color:white;")
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.cur_co2_2 = QtWidgets.QLabel(self.frame_19)
        self.cur_co2_2.setGeometry(QtCore.QRect(20, 40, 101, 61))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.cur_co2_2.setFont(font)
        self.cur_co2_2.setStyleSheet("background:transparent;\n"
"color:white;")
        self.cur_co2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cur_co2_2.setObjectName("cur_co2_2")
        self.graphicsView = PlotWidget(self.page_2)
        self.graphicsView.setGeometry(QtCore.QRect(220, 20, 785, 341))
        self.graphicsView.setStyleSheet("border:transparent;\n"
"border-radius:4px;\n"
"background-color:white;")
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView.raise_()
        self.unfix_check.raise_()
        self.fix_check.raise_()
        self.temp_check.raise_()
        self.frame_17.raise_()
        self.frame_18.raise_()
        self.frame_19.raise_()
        self.humid_check.raise_()
        self.co2_check.raise_()
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.frame_15 = QtWidgets.QFrame(self.page_3)
        self.frame_15.setGeometry(QtCore.QRect(680, 10, 331, 351))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.label_21 = QtWidgets.QLabel(self.frame_15)
        self.label_21.setGeometry(QtCore.QRect(10, 10, 315, 41))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color:white;\n"
"background-color:rgb(1, 255, 9);\n"
"border-top-left-radius:5px;\n"
"border-top-right-radius:5px;")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.frame_16 = QtWidgets.QFrame(self.frame_15)
        self.frame_16.setGeometry(QtCore.QRect(10, 40, 315, 311))
        self.frame_16.setStyleSheet("background-color:white;\n"
"border-radius:5px")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.label_23 = QtWidgets.QLabel(self.frame_16)
        self.label_23.setGeometry(QtCore.QRect(40, 120, 91, 21))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("background:transparent;\n"
"color:rgb(100,100,100);")
        self.label_23.setObjectName("label_23")
        self.connect = QtWidgets.QPushButton(self.frame_16)
        self.connect.setGeometry(QtCore.QRect(110, 250, 105, 41))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.connect.setFont(font)
        self.connect.setStyleSheet("border:1px solid rgb(220,220,220);\n"
"background-color:white;\n"
"border-radius:4px;\n"
"color:rgb(100,100,100);")
        self.connect.setObjectName("connect")
        self.coms = QtWidgets.QComboBox(self.frame_16)
        self.coms.setGeometry(QtCore.QRect(150, 110, 111, 41))
        self.coms.setStyleSheet("border:1px solid rgb(220,220,220);")
        self.coms.setObjectName("coms")
        self.frame_16.raise_()
        self.label_21.raise_()
        self.frame_4 = QtWidgets.QFrame(self.page_3)
        self.frame_4.setGeometry(QtCore.QRect(12, 10, 671, 351))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 651, 41))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white;\n"
"background-color:rgb(1, 255, 9);\n"
"border-top-left-radius:5px;\n"
"border-top-right-radius:5px;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setGeometry(QtCore.QRect(10, 30, 651, 321))
        self.frame_5.setStyleSheet("background-color:white;\n"
"border-radius:5px")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame_5)
        self.stackedWidget_2.setGeometry(QtCore.QRect(20, 40, 611, 261))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.frame_20 = QtWidgets.QFrame(self.page_4)
        self.frame_20.setGeometry(QtCore.QRect(307, 0, 301, 261))
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.label_35 = QtWidgets.QLabel(self.frame_20)
        self.label_35.setGeometry(QtCore.QRect(10, 10, 285, 39))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("color:white;\n"
"background-color:rgb(1, 255, 9);\n"
"border-top-left-radius:5px;\n"
"border-top-right-radius:5px;\n"
"border-bottom-left-radius:0px;\n"
"border-bottom-right-radius:0px")
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.frame_21 = QtWidgets.QFrame(self.frame_20)
        self.frame_21.setGeometry(QtCore.QRect(10, 30, 285, 221))
        self.frame_21.setStyleSheet("background-color:white;\n"
"border-radius:5px;\n"
"border:1px solid rgb(220,220,220);")
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.humid_freq_h = QtWidgets.QSpinBox(self.frame_21)
        self.humid_freq_h.setGeometry(QtCore.QRect(80, 75, 51, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        self.humid_freq_h.setFont(font)
        self.humid_freq_h.setMaximum(100)
        self.humid_freq_h.setObjectName("humid_freq_h")
        self.humid_act_h = QtWidgets.QSpinBox(self.frame_21)
        self.humid_act_h.setGeometry(QtCore.QRect(80, 125, 51, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        self.humid_act_h.setFont(font)
        self.humid_act_h.setMaximum(100)
        self.humid_act_h.setObjectName("humid_act_h")
        self.label_45 = QtWidgets.QLabel(self.frame_21)
        self.label_45.setGeometry(QtCore.QRect(30, 80, 51, 21))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("background:transparent;\n"
"border:transparent;\n"
"color:rgb(100,100,100);")
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.frame_21)
        self.label_46.setGeometry(QtCore.QRect(30, 130, 51, 21))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet("background:transparent;\n"
"border:transparent;\n"
"color:rgb(100,100,100);")
        self.label_46.setObjectName("label_46")
        self.label_48 = QtWidgets.QLabel(self.frame_21)
        self.label_48.setGeometry(QtCore.QRect(135, 80, 51, 21))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setStyleSheet("background:transparent;\n"
"border:transparent;\n"
"color:rgb(100,100,100);")
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.frame_21)
        self.label_49.setGeometry(QtCore.QRect(135, 130, 51, 21))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setStyleSheet("background:transparent;\n"
"border:transparent;\n"
"color:rgb(100,100,100);")
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.frame_21)
        self.label_50.setGeometry(QtCore.QRect(240, 80, 51, 21))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setStyleSheet("background:transparent;\n"
"border:transparent;\n"
"color:rgb(100,100,100);")
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.frame_21)
        self.label_51.setGeometry(QtCore.QRect(240, 130, 51, 21))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setStyleSheet("background:transparent;\n"
"border:transparent;\n"
"color:rgb(100,100,100);")
        self.label_51.setObjectName("label_51")
        self.humid_freq_m = QtWidgets.QSpinBox(self.frame_21)
        self.humid_freq_m.setGeometry(QtCore.QRect(185, 75, 51, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        self.humid_freq_m.setFont(font)
        self.humid_freq_m.setMaximum(60)
        self.humid_freq_m.setObjectName("humid_freq_m")
        self.humid_act_m = QtWidgets.QSpinBox(self.frame_21)
        self.humid_act_m.setGeometry(QtCore.QRect(185, 125, 51, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        self.humid_act_m.setFont(font)
        self.humid_act_m.setMaximum(60)
        self.humid_act_m.setObjectName("humid_act_m")
        self.frame_21.raise_()
        self.label_35.raise_()
        self.manu_apply = QtWidgets.QPushButton(self.page_4)
        self.manu_apply.setGeometry(QtCore.QRect(90, 220, 105, 41))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.manu_apply.setFont(font)
        self.manu_apply.setStyleSheet("border:1px solid rgb(220,220,220);\n"
"background-color:white;\n"
"border-radius:4px;\n"
"color:rgb(100,100,100);")
        self.manu_apply.setObjectName("manu_apply")
        self.label_24 = QtWidgets.QLabel(self.page_4)
        self.label_24.setGeometry(QtCore.QRect(10, 20, 91, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("background:transparent;\n"
"color:rgb(100,100,100);")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.page_4)
        self.label_25.setGeometry(QtCore.QRect(10, 70, 91, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("background:transparent;\n"
"color:rgb(100,100,100);")
        self.label_25.setObjectName("label_25")
        self.label_34 = QtWidgets.QLabel(self.page_4)
        self.label_34.setGeometry(QtCore.QRect(10, 170, 91, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("background:transparent;\n"
"color:rgb(100,100,100);")
        self.label_34.setObjectName("label_34")
        self.label_36 = QtWidgets.QLabel(self.page_4)
        self.label_36.setGeometry(QtCore.QRect(10, 120, 91, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("background:transparent;\n"
"color:rgb(100,100,100);")
        self.label_36.setObjectName("label_36")
        self.manu_temp = QtWidgets.QSpinBox(self.page_4)
        self.manu_temp.setGeometry(QtCore.QRect(60, 20, 61, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        self.manu_temp.setFont(font)
        self.manu_temp.setStyleSheet("border:1px solid rgb(220,220,220);")
        self.manu_temp.setMinimum(-50)
        self.manu_temp.setMaximum(50)
        self.manu_temp.setObjectName("manu_temp")
        self.manu_humid = QtWidgets.QSpinBox(self.page_4)
        self.manu_humid.setGeometry(QtCore.QRect(60, 70, 61, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        self.manu_humid.setFont(font)
        self.manu_humid.setStyleSheet("border:1px solid rgb(220,220,220);")
        self.manu_humid.setMaximum(100)
        self.manu_humid.setObjectName("manu_humid")
        self.manu_co2 = QtWidgets.QSpinBox(self.page_4)
        self.manu_co2.setGeometry(QtCore.QRect(60, 120, 61, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        self.manu_co2.setFont(font)
        self.manu_co2.setStyleSheet("border:1px solid rgb(220,220,220);")
        self.manu_co2.setMaximum(1000)
        self.manu_co2.setObjectName("manu_co2")
        self.manu_days = QtWidgets.QSpinBox(self.page_4)
        self.manu_days.setGeometry(QtCore.QRect(110, 170, 51, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        self.manu_days.setFont(font)
        self.manu_days.setStyleSheet("border:1px solid rgb(220,220,220);")
        self.manu_days.setMaximum(50)
        self.manu_days.setObjectName("manu_days")
        self.label_52 = QtWidgets.QLabel(self.page_4)
        self.label_52.setGeometry(QtCore.QRect(170, 170, 31, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_52.setFont(font)
        self.label_52.setStyleSheet("background:transparent;\n"
"color:rgb(100,100,100);")
        self.label_52.setObjectName("label_52")
        self.manu_hours = QtWidgets.QSpinBox(self.page_4)
        self.manu_hours.setGeometry(QtCore.QRect(200, 170, 51, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        self.manu_hours.setFont(font)
        self.manu_hours.setStyleSheet("border:1px solid rgb(220,220,220);")
        self.manu_hours.setMaximum(24)
        self.manu_hours.setObjectName("manu_hours")
        self.label_53 = QtWidgets.QLabel(self.page_4)
        self.label_53.setGeometry(QtCore.QRect(260, 170, 41, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_53.setFont(font)
        self.label_53.setStyleSheet("background:transparent;\n"
"color:rgb(100,100,100);")
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.page_4)
        self.label_54.setGeometry(QtCore.QRect(130, 20, 31, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setStyleSheet("background:transparent;\n"
"color:rgb(100,100,100);")
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.page_4)
        self.label_55.setGeometry(QtCore.QRect(130, 70, 31, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setStyleSheet("background:transparent;\n"
"color:rgb(100,100,100);")
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.page_4)
        self.label_56.setGeometry(QtCore.QRect(130, 120, 31, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setStyleSheet("background:transparent;\n"
"color:rgb(100,100,100);")
        self.label_56.setObjectName("label_56")
        self.manu_humid_range = QtWidgets.QSpinBox(self.page_4)
        self.manu_humid_range.setGeometry(QtCore.QRect(170, 70, 61, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        self.manu_humid_range.setFont(font)
        self.manu_humid_range.setStyleSheet("border:1px solid rgb(220,220,220);")
        self.manu_humid_range.setMaximum(100)
        self.manu_humid_range.setObjectName("manu_humid_range")
        self.manu_co2_range = QtWidgets.QSpinBox(self.page_4)
        self.manu_co2_range.setGeometry(QtCore.QRect(170, 120, 61, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        self.manu_co2_range.setFont(font)
        self.manu_co2_range.setStyleSheet("border:1px solid rgb(220,220,220);")
        self.manu_co2_range.setMaximum(1000)
        self.manu_co2_range.setObjectName("manu_co2_range")
        self.manu_temp_range = QtWidgets.QSpinBox(self.page_4)
        self.manu_temp_range.setGeometry(QtCore.QRect(170, 20, 61, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        self.manu_temp_range.setFont(font)
        self.manu_temp_range.setStyleSheet("border:1px solid rgb(220,220,220);")
        self.manu_temp_range.setMinimum(-50)
        self.manu_temp_range.setMaximum(50)
        self.manu_temp_range.setObjectName("manu_temp_range")
        self.label_57 = QtWidgets.QLabel(self.page_4)
        self.label_57.setGeometry(QtCore.QRect(240, 120, 41, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_57.setFont(font)
        self.label_57.setStyleSheet("background:transparent;\n"
"color:rgb(100,100,100);")
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.page_4)
        self.label_58.setGeometry(QtCore.QRect(240, 70, 41, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_58.setFont(font)
        self.label_58.setStyleSheet("background:transparent;\n"
"color:rgb(100,100,100);")
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.page_4)
        self.label_59.setGeometry(QtCore.QRect(230, 20, 31, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_59.setFont(font)
        self.label_59.setStyleSheet("background:transparent;\n"
"color:rgb(100,100,100);")
        self.label_59.setObjectName("label_59")
        self.stackedWidget_2.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.label_60 = QtWidgets.QLabel(self.page_5)
        self.label_60.setGeometry(QtCore.QRect(410, 70, 41, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_60.setFont(font)
        self.label_60.setStyleSheet("background:transparent;\n"
"color:rgb(100,100,100);")
        self.label_60.setObjectName("label_60")
        self.auto_humid = QtWidgets.QSpinBox(self.page_5)
        self.auto_humid.setGeometry(QtCore.QRect(230, 70, 61, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        self.auto_humid.setFont(font)
        self.auto_humid.setStyleSheet("border:1px solid rgb(220,220,220);")
        self.auto_humid.setMaximum(100)
        self.auto_humid.setObjectName("auto_humid")
        self.auto_temp_range = QtWidgets.QSpinBox(self.page_5)
        self.auto_temp_range.setGeometry(QtCore.QRect(340, 20, 61, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        self.auto_temp_range.setFont(font)
        self.auto_temp_range.setStyleSheet("border:1px solid rgb(220,220,220);")
        self.auto_temp_range.setMinimum(-50)
        self.auto_temp_range.setMaximum(50)
        self.auto_temp_range.setObjectName("auto_temp_range")
        self.label_61 = QtWidgets.QLabel(self.page_5)
        self.label_61.setGeometry(QtCore.QRect(180, 70, 91, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_61.setFont(font)
        self.label_61.setStyleSheet("background:transparent;\n"
"color:rgb(100,100,100);")
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(self.page_5)
        self.label_62.setGeometry(QtCore.QRect(300, 120, 31, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_62.setFont(font)
        self.label_62.setStyleSheet("background:transparent;\n"
"color:rgb(100,100,100);")
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QLabel(self.page_5)
        self.label_63.setGeometry(QtCore.QRect(180, 170, 91, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_63.setFont(font)
        self.label_63.setStyleSheet("background:transparent;\n"
"color:rgb(100,100,100);")
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(self.page_5)
        self.label_64.setGeometry(QtCore.QRect(410, 120, 41, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_64.setFont(font)
        self.label_64.setStyleSheet("background:transparent;\n"
"color:rgb(100,100,100);")
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(self.page_5)
        self.label_65.setGeometry(QtCore.QRect(180, 20, 91, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_65.setFont(font)
        self.label_65.setStyleSheet("background:transparent;\n"
"color:rgb(100,100,100);")
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(self.page_5)
        self.label_66.setGeometry(QtCore.QRect(330, 170, 31, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_66.setFont(font)
        self.label_66.setStyleSheet("background:transparent;\n"
"color:rgb(100,100,100);")
        self.label_66.setObjectName("label_66")
        self.auto_temp = QtWidgets.QSpinBox(self.page_5)
        self.auto_temp.setGeometry(QtCore.QRect(230, 20, 61, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        self.auto_temp.setFont(font)
        self.auto_temp.setStyleSheet("border:1px solid rgb(220,220,220);")
        self.auto_temp.setMinimum(-50)
        self.auto_temp.setMaximum(50)
        self.auto_temp.setObjectName("auto_temp")
        self.label_67 = QtWidgets.QLabel(self.page_5)
        self.label_67.setGeometry(QtCore.QRect(400, 20, 31, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_67.setFont(font)
        self.label_67.setStyleSheet("background:transparent;\n"
"color:rgb(100,100,100);")
        self.label_67.setObjectName("label_67")
        self.auto_humid_range = QtWidgets.QSpinBox(self.page_5)
        self.auto_humid_range.setGeometry(QtCore.QRect(340, 70, 61, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        self.auto_humid_range.setFont(font)
        self.auto_humid_range.setStyleSheet("border:1px solid rgb(220,220,220);")
        self.auto_humid_range.setMaximum(100)
        self.auto_humid_range.setObjectName("auto_humid_range")
        self.auto_apply = QtWidgets.QPushButton(self.page_5)
        self.auto_apply.setGeometry(QtCore.QRect(260, 220, 105, 41))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.auto_apply.setFont(font)
        self.auto_apply.setStyleSheet("border:1px solid rgb(220,220,220);\n"
"background-color:white;\n"
"border-radius:4px;\n"
"color:rgb(100,100,100);")
        self.auto_apply.setObjectName("auto_apply")
        self.auto_hours = QtWidgets.QSpinBox(self.page_5)
        self.auto_hours.setGeometry(QtCore.QRect(370, 170, 51, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        self.auto_hours.setFont(font)
        self.auto_hours.setStyleSheet("border:1px solid rgb(220,220,220);")
        self.auto_hours.setMaximum(24)
        self.auto_hours.setObjectName("auto_hours")
        self.label_68 = QtWidgets.QLabel(self.page_5)
        self.label_68.setGeometry(QtCore.QRect(430, 170, 41, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_68.setFont(font)
        self.label_68.setStyleSheet("background:transparent;\n"
"color:rgb(100,100,100);")
        self.label_68.setObjectName("label_68")
        self.label_69 = QtWidgets.QLabel(self.page_5)
        self.label_69.setGeometry(QtCore.QRect(300, 70, 31, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_69.setFont(font)
        self.label_69.setStyleSheet("background:transparent;\n"
"color:rgb(100,100,100);")
        self.label_69.setObjectName("label_69")
        self.label_70 = QtWidgets.QLabel(self.page_5)
        self.label_70.setGeometry(QtCore.QRect(180, 120, 91, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_70.setFont(font)
        self.label_70.setStyleSheet("background:transparent;\n"
"color:rgb(100,100,100);")
        self.label_70.setObjectName("label_70")
        self.auto_co2 = QtWidgets.QSpinBox(self.page_5)
        self.auto_co2.setGeometry(QtCore.QRect(230, 120, 61, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        self.auto_co2.setFont(font)
        self.auto_co2.setStyleSheet("border:1px solid rgb(220,220,220);")
        self.auto_co2.setMaximum(1000)
        self.auto_co2.setObjectName("auto_co2")
        self.auto_co2_range = QtWidgets.QSpinBox(self.page_5)
        self.auto_co2_range.setGeometry(QtCore.QRect(340, 120, 61, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        self.auto_co2_range.setFont(font)
        self.auto_co2_range.setStyleSheet("border:1px solid rgb(220,220,220);")
        self.auto_co2_range.setMaximum(1000)
        self.auto_co2_range.setObjectName("auto_co2_range")
        self.label_71 = QtWidgets.QLabel(self.page_5)
        self.label_71.setGeometry(QtCore.QRect(300, 20, 31, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_71.setFont(font)
        self.label_71.setStyleSheet("background:transparent;\n"
"color:rgb(100,100,100);")
        self.label_71.setObjectName("label_71")
        self.auto_days = QtWidgets.QSpinBox(self.page_5)
        self.auto_days.setGeometry(QtCore.QRect(270, 170, 51, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        self.auto_days.setFont(font)
        self.auto_days.setStyleSheet("border:1px solid rgb(220,220,220);")
        self.auto_days.setMaximum(50)
        self.auto_days.setObjectName("auto_days")
        self.label_60.raise_()
        self.auto_temp_range.raise_()
        self.label_61.raise_()
        self.label_62.raise_()
        self.label_63.raise_()
        self.label_64.raise_()
        self.label_65.raise_()
        self.label_66.raise_()
        self.auto_temp.raise_()
        self.label_67.raise_()
        self.auto_humid_range.raise_()
        self.auto_apply.raise_()
        self.auto_hours.raise_()
        self.label_68.raise_()
        self.label_69.raise_()
        self.label_70.raise_()
        self.auto_co2.raise_()
        self.auto_co2_range.raise_()
        self.label_71.raise_()
        self.auto_days.raise_()
        self.auto_humid.raise_()
        self.stackedWidget_2.addWidget(self.page_5)
        self.manual_mode = QtWidgets.QRadioButton(self.frame_4)
        self.manual_mode.setGeometry(QtCore.QRect(370, 20, 90, 21))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(12)
        self.manual_mode.setFont(font)
        self.manual_mode.setStyleSheet("background-color:transparent;\n"
"color:rgb(50,50,50);")
        self.manual_mode.setChecked(True)
        self.manual_mode.setObjectName("manual_mode")
        self.auto_mode = QtWidgets.QRadioButton(self.frame_4)
        self.auto_mode.setGeometry(QtCore.QRect(480, 20, 90, 21))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(12)
        self.auto_mode.setFont(font)
        self.auto_mode.setStyleSheet("background-color:transparent;\n"
"color:rgb(50,50,50);")
        self.auto_mode.setObjectName("auto_mode")
        self.frame_5.raise_()
        self.label_2.raise_()
        self.manual_mode.raise_()
        self.auto_mode.raise_()
        self.stackedWidget.addWidget(self.page_3)
        self.power = QtWidgets.QPushButton(self.centralwidget)
        self.power.setGeometry(QtCore.QRect(900, 470, 105, 105))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.power.setFont(font)
        self.power.setStyleSheet("QPushButton{border:1px solid rgb(220,220,220);\n"
"background-color:white;\n"
"border-top-left-radius:4px;\n"
"border-bottom-left-radius:4px;\n"
"color:rgb(100,100,100);}\n"
"QPushButton:checked{\n"
"border:1px solid rgb(220,220,220);\n"
"background-color:grey;\n"
"border-top-left-radius:4px;\n"
"border-bottom-left-radius:4px;\n"
"color:white;}")
        self.power.setCheckable(True)
        self.power.setObjectName("power")
        self.humidifier = QtWidgets.QPushButton(self.centralwidget)
        self.humidifier.setGeometry(QtCore.QRect(461, 470, 105, 105))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.humidifier.setFont(font)
        self.humidifier.setStyleSheet("QPushButton{border:1px solid rgb(220,220,220);\n"
"background-color:white;\n"
"border-top-left-radius:4px;\n"
"border-bottom-left-radius:4px;\n"
"color:rgb(100,100,100);}\n"
"QPushButton:checked{\n"
"border:1px solid rgb(220,220,220);\n"
"background-color:grey;\n"
"border-top-left-radius:4px;\n"
"border-bottom-left-radius:4px;\n"
"color:white;}")
        self.humidifier.setCheckable(True)
        self.humidifier.setObjectName("humidifier")
        self.heater = QtWidgets.QPushButton(self.centralwidget)
        self.heater.setGeometry(QtCore.QRect(357, 470, 105, 105))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.heater.setFont(font)
        self.heater.setStyleSheet("QPushButton{border:1px solid rgb(220,220,220);\n"
"background-color:white;\n"
"border-top-left-radius:4px;\n"
"border-bottom-left-radius:4px;\n"
"color:rgb(100,100,100);}\n"
"QPushButton:checked{\n"
"border:1px solid rgb(220,220,220);\n"
"background-color:grey;\n"
"border-top-left-radius:4px;\n"
"border-bottom-left-radius:4px;\n"
"color:white;}")
        self.heater.setCheckable(True)
        self.heater.setObjectName("heater")
        self.led = QtWidgets.QPushButton(self.centralwidget)
        self.led.setGeometry(QtCore.QRect(773, 470, 105, 105))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.led.setFont(font)
        self.led.setStyleSheet("QPushButton{border:1px solid rgb(220,220,220);\n"
"background-color:white;\n"
"border-top-left-radius:4px;\n"
"border-bottom-left-radius:4px;\n"
"color:rgb(100,100,100);}\n"
"QPushButton:checked{\n"
"border:1px solid rgb(220,220,220);\n"
"background-color:grey;\n"
"border-top-left-radius:4px;\n"
"border-bottom-left-radius:4px;\n"
"color:white;}")
        self.led.setCheckable(True)
        self.led.setObjectName("led")
        self.fan = QtWidgets.QPushButton(self.centralwidget)
        self.fan.setGeometry(QtCore.QRect(565, 470, 105, 105))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.fan.setFont(font)
        self.fan.setStyleSheet("QPushButton{border:1px solid rgb(220,220,220);\n"
"background-color:white;\n"
"border-top-left-radius:4px;\n"
"border-bottom-left-radius:4px;\n"
"color:rgb(100,100,100);}\n"
"QPushButton:checked{\n"
"border:1px solid rgb(220,220,220);\n"
"background-color:grey;\n"
"border-top-left-radius:4px;\n"
"border-bottom-left-radius:4px;\n"
"color:white;}")
        self.fan.setCheckable(True)
        self.fan.setObjectName("fan")
        self.dryer = QtWidgets.QPushButton(self.centralwidget)
        self.dryer.setGeometry(QtCore.QRect(669, 470, 105, 105))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.dryer.setFont(font)
        self.dryer.setStyleSheet("QPushButton{border:1px solid rgb(220,220,220);\n"
"background-color:white;\n"
"border-top-left-radius:4px;\n"
"border-bottom-left-radius:4px;\n"
"color:rgb(100,100,100);}\n"
"QPushButton:checked{\n"
"border:1px solid rgb(220,220,220);\n"
"background-color:grey;\n"
"border-top-left-radius:4px;\n"
"border-bottom-left-radius:4px;\n"
"color:white;}")
        self.dryer.setCheckable(True)
        self.dryer.setObjectName("dryer")
        self.frame_22 = QtWidgets.QFrame(self.centralwidget)
        self.frame_22.setGeometry(QtCore.QRect(10, 470, 341, 111))
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.main = QtWidgets.QPushButton(self.frame_22)
        self.main.setGeometry(QtCore.QRect(12, 0, 105, 105))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.main.setFont(font)
        self.main.setStyleSheet("QPushButton{border:1px solid rgb(220,220,220);\n"
"background-color:white;\n"
"border-top-left-radius:4px;\n"
"border-bottom-left-radius:4px;\n"
"color:rgb(100,100,100);}\n"
"QPushButton:checked{\n"
"border:1px solid rgb(220,220,220);\n"
"background-color:grey;\n"
"border-top-left-radius:4px;\n"
"border-bottom-left-radius:4px;\n"
"color:white;}\n"
"")
        self.main.setCheckable(True)
        self.main.setChecked(True)
        self.main.setAutoRepeat(False)
        self.main.setAutoExclusive(True)
        self.main.setObjectName("main")
        self.graph = QtWidgets.QPushButton(self.frame_22)
        self.graph.setGeometry(QtCore.QRect(116, 0, 105, 105))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.graph.setFont(font)
        self.graph.setStyleSheet("QPushButton{border:1px solid rgb(220,220,220);\n"
"background-color:white;\n"
"border-top-left-radius:4px;\n"
"border-bottom-left-radius:4px;\n"
"color:rgb(100,100,100);}\n"
"QPushButton:checked{\n"
"border:1px solid rgb(220,220,220);\n"
"background-color:grey;\n"
"border-top-left-radius:4px;\n"
"border-bottom-left-radius:4px;\n"
"color:white;}")
        self.graph.setCheckable(True)
        self.graph.setAutoRepeat(False)
        self.graph.setAutoExclusive(True)
        self.graph.setObjectName("graph")
        self.settings = QtWidgets.QPushButton(self.frame_22)
        self.settings.setGeometry(QtCore.QRect(220, 0, 105, 105))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.settings.setFont(font)
        self.settings.setStyleSheet("QPushButton{border:1px solid rgb(220,220,220);\n"
"background-color:white;\n"
"border-top-left-radius:4px;\n"
"border-bottom-left-radius:4px;\n"
"color:rgb(100,100,100);}\n"
"QPushButton:checked{\n"
"border:1px solid rgb(220,220,220);\n"
"background-color:grey;\n"
"border-top-left-radius:4px;\n"
"border-bottom-left-radius:4px;\n"
"color:white;}")
        self.settings.setCheckable(True)
        self.settings.setAutoRepeat(False)
        self.settings.setAutoExclusive(True)
        self.settings.setObjectName("settings")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_32.setText(_translate("MainWindow", "MushFarm Monitoring System"))
        self.label_7.setText(_translate("MainWindow", "습도"))
        self.cur_humid_1.setText(_translate("MainWindow", "100"))
        self.label_9.setText(_translate("MainWindow", "설정  |"))
        self.settings_humid.setText(_translate("MainWindow", "100"))
        self.label_16.setText(_translate("MainWindow", "%"))
        self.label_19.setText(_translate("MainWindow", "%"))
        self.label_11.setText(_translate("MainWindow", "Co2"))
        self.cur_co2_1.setText(_translate("MainWindow", "1000"))
        self.label_13.setText(_translate("MainWindow", "설정  |"))
        self.settings_co2.setText(_translate("MainWindow", "1000"))
        self.label_17.setText(_translate("MainWindow", "ppm"))
        self.label_18.setText(_translate("MainWindow", "ppm"))
        self.label_30.setText(_translate("MainWindow", "센서 수신 시간"))
        self.sens_time.setText(_translate("MainWindow", "12 : 59 : 59"))
        self.label_26.setText(_translate("MainWindow", "진행률"))
        self.progress.setText(_translate("MainWindow", "100"))
        self.label_31.setText(_translate("MainWindow", "%"))
        self.label_28.setText(_translate("MainWindow", "현재 시간"))
        self.cur_time.setText(_translate("MainWindow", "12 : 59 : 59"))
        self.label.setText(_translate("MainWindow", "온도"))
        self.cur_temp_1.setText(_translate("MainWindow", "99.9"))
        self.label_5.setText(_translate("MainWindow", "설정  |"))
        self.settings_temp.setText(_translate("MainWindow", "99.9"))
        self.label_15.setText(_translate("MainWindow", " °C"))
        self.label_20.setText(_translate("MainWindow", " °C"))
        self.unfix_check.setText(_translate("MainWindow", "변동"))
        self.fix_check.setText(_translate("MainWindow", "고정"))
        self.temp_check.setText(_translate("MainWindow", "온도"))
        self.humid_check.setText(_translate("MainWindow", "습도"))
        self.co2_check.setText(_translate("MainWindow", "Co2"))
        self.cur_temp_2.setText(_translate("MainWindow", "99.9"))
        self.label_38.setText(_translate("MainWindow", "온도"))
        self.label_40.setText(_translate("MainWindow", " °C"))
        self.label_44.setText(_translate("MainWindow", "습도"))
        self.label_41.setText(_translate("MainWindow", "%"))
        self.cur_humid_2.setText(_translate("MainWindow", "100"))
        self.label_47.setText(_translate("MainWindow", "Co2"))
        self.label_42.setText(_translate("MainWindow", "ppm"))
        self.cur_co2_2.setText(_translate("MainWindow", "9999"))
        self.label_21.setText(_translate("MainWindow", "기타 설정"))
        self.label_23.setText(_translate("MainWindow", "연결 포트"))
        self.connect.setText(_translate("MainWindow", "연결"))
        self.label_2.setText(_translate("MainWindow", "재배 동작 모드 설정                      "))
        self.label_35.setText(_translate("MainWindow", "가습기 동작 설정"))
        self.label_45.setText(_translate("MainWindow", "주기"))
        self.label_46.setText(_translate("MainWindow", "동작"))
        self.label_48.setText(_translate("MainWindow", "시간"))
        self.label_49.setText(_translate("MainWindow", "시간"))
        self.label_50.setText(_translate("MainWindow", "분"))
        self.label_51.setText(_translate("MainWindow", "분"))
        self.manu_apply.setText(_translate("MainWindow", "적용"))
        self.label_24.setText(_translate("MainWindow", "온도"))
        self.label_25.setText(_translate("MainWindow", "습도"))
        self.label_34.setText(_translate("MainWindow", "재배 시간"))
        self.label_36.setText(_translate("MainWindow", "Co2"))
        self.label_52.setText(_translate("MainWindow", "일"))
        self.label_53.setText(_translate("MainWindow", "시간"))
        self.label_54.setText(_translate("MainWindow", " ±"))
        self.label_55.setText(_translate("MainWindow", " ±"))
        self.label_56.setText(_translate("MainWindow", " ±"))
        self.label_57.setText(_translate("MainWindow", "ppm"))
        self.label_58.setText(_translate("MainWindow", "%"))
        self.label_59.setText(_translate("MainWindow", " °C"))
        self.label_60.setText(_translate("MainWindow", "%"))
        self.label_61.setText(_translate("MainWindow", "습도"))
        self.label_62.setText(_translate("MainWindow", " ±"))
        self.label_63.setText(_translate("MainWindow", "동작 시간"))
        self.label_64.setText(_translate("MainWindow", "ppm"))
        self.label_65.setText(_translate("MainWindow", "온도"))
        self.label_66.setText(_translate("MainWindow", "일"))
        self.label_67.setText(_translate("MainWindow", " °C"))
        self.auto_apply.setText(_translate("MainWindow", "적용"))
        self.label_68.setText(_translate("MainWindow", "시간"))
        self.label_69.setText(_translate("MainWindow", " ±"))
        self.label_70.setText(_translate("MainWindow", "Co2"))
        self.label_71.setText(_translate("MainWindow", " ±"))
        self.manual_mode.setText(_translate("MainWindow", "수동 모드"))
        self.auto_mode.setText(_translate("MainWindow", "자동 모드"))
        self.power.setText(_translate("MainWindow", "\n"
"\n"
"전원"))
        self.humidifier.setText(_translate("MainWindow", "\n"
"\n"
"가습기"))
        self.heater.setText(_translate("MainWindow", "\n"
"\n"
"히터"))
        self.led.setText(_translate("MainWindow", "\n"
"\n"
"조명"))
        self.fan.setText(_translate("MainWindow", "\n"
"\n"
"송풍기"))
        self.dryer.setText(_translate("MainWindow", "\n"
"\n"
"건조기"))
        self.main.setText(_translate("MainWindow", "\n"
"\n"
"메인"))
        self.graph.setText(_translate("MainWindow", "\n"
"\n"
"그래프"))
        self.settings.setText(_translate("MainWindow", "\n"
"\n"
"설정"))


from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
